"""Shared class mappings for MIRA dataset conversion."""

TACO_REMAP = {
    "Aluminium foil": 1,
    "Battery": 4,
    "Aluminium blister pack": 4,
    "Carded blister pack": 4,
    "Other plastic bottle": 3,
    "Clear plastic bottle": 3,
    "Glass bottle": 0,
    "Plastic bottle cap": 3,
    "Metal bottle cap": 1,
    "Broken glass": 0,
    "Food Can": 1,
    "Aerosol": 1,
    "Drink can": 1,
    "Toilet tube": 2,
    "Other carton": 2,
    "Egg carton": 2,
    "Drink carton": 2,
    "Corrugated carton": 2,
    "Meal carton": 2,
    "Pizza box": 2,
    "Paper cup": 2,
    "Disposable plastic cup": 3,
    "Foam cup": 3,
    "Glass cup": 0,
    "Other plastic cup": 3,
    "Food waste": 4,
    "Glass jar": 0,
    "Plastic lid": 3,
    "Metal lid": 1,
    "Other plastic": 3,
    "Magazine paper": 2,
    "Tissues": 2,
    "Wrapping paper": 2,
    "Normal paper": 2,
    "Paper bag": 2,
    "Plastified paper bag": 2,
    "Plastic film": 3,
    "Six pack rings": 3,
    "Garbage bag": 3,
    "Other plastic wrapper": 3,
    "Single-use carrier bag": 3,
    "Polypropylene bag": 3,
    "Crisp packet": 3,
    "Spread tub": 3,
    "Tupperware": 3,
    "Disposable food container": 3,
    "Foam food container": 3,
    "Other plastic container": 3,
    "Plastic gloves": 3,
    "Plastic utensils": 3,
    "Pop tab": 1,
    "Rope & strings": 4,
    "Scrap metal": 1,
    "Shoe": 4,
    "Squeezable tube": 3,
    "Plastic straw": 3,
    "Paper straw": 2,
    "Styrofoam piece": 3,
    "Unlabeled litter": 4,
    "Cigarette": 4,
}

TRASHNET_FOLDER_MAP = {
    "cardboard": 2,
    "glass": 0,
    "metal": 1,
    "paper": 2,
    "plastic": 3,
    "trash": 4,
}
