"""Upload trained MIRA models to Hugging Face Hub.

Usage:
    python scripts/push_to_hub.py --model models/detection/mira_exp014.pt --repo-id jeremy341/mira-ai-models
    python scripts/push_to_hub.py --model models/detection/mira_exp014.pt --repo-id jeremy341/mira-ai-models --tag exp014
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _find_model_variants(model_path: Path) -> dict[str, Path]:
    """Find .pt, .tflite, .onnx variants alongside the main model."""
    stem = model_path.stem
    parent = model_path.parent
    variants: dict[str, Path] = {}

    if model_path.exists():
        variants["pt"] = model_path

    for suffix, key in [(".tflite", "tflite"), ("_int8.tflite", "int8tflite"), (".onnx", "onnx")]:
        candidate = parent / f"{stem}{suffix}"
        if candidate.exists():
            variants[key] = candidate

    return variants


def _parse_training_results(model_path: Path) -> dict:
    """Try to read training metrics from results.csv or results.txt."""
    results_dir = model_path.parent.parent
    results: dict = {}

    for name in ["results.csv", "results.txt"]:
        results_file = results_dir / name
        if results_file.exists():
            try:
                import csv

                with open(results_file, encoding="utf-8") as f:
                    reader = csv.DictReader(f)
                    rows = list(reader)
                    if rows:
                        last = rows[-1]
                        results = {k.strip(): v.strip() for k, v in last.items() if v and v.strip()}
            except Exception:
                pass
            break

    return results


def _generate_model_card(
    model_path: Path,
    repo_id: str,
    metrics: dict,
    exp_name: str,
    extra_info: str | None,
) -> str:
    """Generate a Markdown model card."""
    lines = [
        f"# MIRA — {exp_name}",
        "",
        "Machine Intelligence for Recycling Automation — YOLO11 detection model.",
        "",
        "## Model Details",
        "",
        "- **Base model:** YOLO11n",
        "- **Classes:** glass, metal, paper, plastic, trash",
        "- **Task:** Object detection for waste sorting",
        "- **Framework:** Ultralytics YOLO",
        "",
    ]

    if metrics:
        lines.append("## Training Metrics")
        lines.append("")
        for key, val in metrics.items():
            lines.append(f"- **{key}:** {val}")
        lines.append("")

    if extra_info:
        lines.append("## Additional Notes")
        lines.append("")
        lines.append(extra_info)
        lines.append("")

    lines.extend(
        [
            "## Usage",
            "",
            "```python",
            "from ultralytics import YOLO",
            "",
            f'model = YOLO("{model_path.name}")',
            "results = model.val(data='dataset.yaml')",
            "```",
            "",
            "## Export",
            "",
            "```bash",
            "yolo export model=best.pt format=tflite int8=True",
            "yolo export model=best.pt format=onnx",
            "```",
            "",
            "---",
            "",
            "*Generated by MIRA — Machine Intelligence for Recycling Automation*",
        ]
    )

    return "\n".join(lines)


def _load_experiment_metrics(project_root: Path, model_path: Path) -> tuple[dict, str]:
    """Load metrics from experiment results directory."""
    results: dict = {}
    exp_name = model_path.stem

    results_csv = project_root / "runs" / exp_name / "results.csv"
    if results_csv.exists():
        try:
            import csv

            with open(results_csv, encoding="utf-8") as f:
                reader = csv.DictReader(f)
                rows = list(reader)
                if rows:
                    last = rows[-1]
                    results = {k.strip(): v.strip() for k, v in last.items() if v and v.strip()}
        except Exception:
            pass

    return results, exp_name


def push_to_hub(
    model_path: str | Path,
    repo_id: str,
    tag: str | None = None,
    token: str | None = None,
    extra_info: str | None = None,
) -> str:
    """Push model and variants to Hugging Face Hub.

    Returns the URL of the uploaded model.
    """
    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        print("Error: huggingface_hub is required. Install with: pip install huggingface_hub", file=sys.stderr)
        sys.exit(1)

    model_path = Path(model_path)
    if not model_path.exists():
        print(f"Error: Model not found: {model_path}", file=sys.stderr)
        sys.exit(1)

    project_root = model_path.resolve().parent.parent.parent
    metrics, exp_name = _load_experiment_metrics(project_root, model_path)
    tag = tag or exp_name

    api = HfApi(token=token)

    # Create repo if it doesn't exist
    try:
        create_repo(repo_id, repo_type="model", token=token, exist_ok=True)
        print(f"Repository ready: https://huggingface.co/{repo_id}")
    except Exception as e:
        print(f"Warning: Could not create repo: {e}", file=sys.stderr)

    # Find model variants
    variants = _find_model_variants(model_path)
    print(f"Found {len(variants)} model variant(s): {', '.join(variants.keys())}")

    # Upload each variant
    for fmt, path in variants.items():
        filename = (
            f"best.{fmt}"
            if fmt == "pt"
            else f"best_{fmt.replace('.', '_')}.{fmt.split('.')[-1]}"
            if "." in fmt
            else f"best.{fmt}"
        )
        if fmt == "pt":
            filename = f"{tag}.pt"
        elif fmt == "int8tflite":
            filename = f"{tag}_int8.tflite"
        elif fmt == "tflite":
            filename = f"{tag}.tflite"
        elif fmt == "onnx":
            filename = f"{tag}.onnx"
        else:
            filename = f"{tag}.{fmt}"

        print(f"  Uploading {path.name} -> {repo_id}/{filename}")
        api.upload_file(
            path_or_fileobj=str(path),
            path_in_repo=filename,
            repo_id=repo_id,
            repo_type="model",
            token=token,
        )

    # Generate and upload model card
    model_card = _generate_model_card(model_path, repo_id, metrics, exp_name, extra_info)
    api.upload_file(
        path_or_fileobj=model_card.encode("utf-8"),
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="model",
        token=token,
    )
    print("  Uploaded README.md (model card)")

    url = f"https://huggingface.co/{repo_id}"
    print(f"\nDone! Model available at: {url}")
    return url


def main():
    parser = argparse.ArgumentParser(description="Upload trained models to Hugging Face Hub")
    parser.add_argument("--model", type=str, required=True, help="Path to .pt model file")
    parser.add_argument(
        "--repo-id", type=str, required=True, help="HuggingFace repo ID (e.g. jeremy341/mira-ai-models)"
    )
    parser.add_argument("--tag", type=str, default=None, help="Model tag/name (default: experiment name from path)")
    parser.add_argument("--token", type=str, default=None, help="HuggingFace API token (or set HF_TOKEN env var)")
    parser.add_argument("--info", type=str, default=None, help="Extra info to include in model card")
    args = parser.parse_args()

    push_to_hub(
        model_path=args.model,
        repo_id=args.repo_id,
        tag=args.tag,
        token=args.token,
        extra_info=args.info,
    )


if __name__ == "__main__":
    main()
